---
title: "Cox_analysis"
author: "Marissa Wright-LaGreca"
date: "26/04/2022"
output: html_document
---



Data=read.table("Data_low_dose.txt",header=TRUE)





********Cox Analysis*******
install.packages("survival")

install.packages("survminer")

install.packages("dplyr")

install.packages("ggplot2")

install.packages("ggpubr")

***

library(survival)

library(survminer)

library(dplyr)

library(ggplot2)

library(ggpubr)

*******

setwd("/Users/maris/OneDrive/Documents/USRA2021/mb2021")

getwd()

list.files(path=".")

****

Data=read.table("Data_low_dose.txt",header=TRUE)

head(Data)

surv_object = Surv(time=Data$TD, event=Data$Binary)

surv_object

fit1 = survfit(surv_object~treatment, data=Data)

summary(fit1)


****warning with code below - orders treatment alphabetically rather than what appears on data sheet - keep in mind and match results with summary(fit) function results

ggsurvplot(fit1, data=Data, pval = TRUE, legend = "bottom", legend.title="Treatment", font.legend =c(9,"plain","black"), legend.labs=c("Control","High_salinity","Low_salinity"))


*****fit a cox proportional hazards model for size and family*****

****note family as text in data file****

fit.coxph =coxph(Surv(TD,Binary)~treatment,data=Data)

summary(fit.coxph)

ggforest(fit.coxph, data=Data)



